server:
  servlet:
    context-path: /query/bookings
  port: ${PORT:8086}

spring:
  application:
    name: bookings-service-query
  cloud:
    stream:
      bindings:
        input:
          destination: bookings-events
          consumer.headerMode: headers
          group: cargo-location-summary
          content-type: application/*+avro
      kafka:
        binder:
          headers: event_type,kafka_messageKey
      schema:
        avro:
          dynamicSchemaGenerationEnabled: true
      schemaRegistryClient:
        endpoint: http://localhost:8111
        cached: true